# export model in gltf format
# note: Blender under version 2.8 does not support exporting gltf by default

import bpy
import os

COPYRIGHT = "generated by blender-3d-tiler"

EXPORT_MODE = 'GLTF_SEPARATE' # 'GLB', 'GLTF_EMBEDDED', 'GLTF_SEPARATE'

EXPORT_SELECTED = False
EXPORT_ANIMATION = False
EXPORT_LIGHT = True
EXPORT_CAMERA = True

FILEPATH = "\\path\\to\\your\\model.gltf"

bpy.ops.export_scene.gltf(
    export_format = 'GLTF_SEPARATE',
    export_copyright = COPYRIGHT,
    export_texcoords = True,
    export_normals = True,
    export_materials = True,
    export_colors = True,
    export_cameras = EXPORT_CAMERA,
    export_selected = EXPORT_SELECTED,
    export_extras = False,
    export_yup = True,
    export_apply = False,
    export_animations = EXPORT_ANIMATION,
    export_frame_range = EXPORT_ANIMATION,
    export_lights = EXPORT_LIGHT,
    filepath = FILEPATH
)
